# Programação Funcional

### Lambda

In [ ]:
quadrado = lambda num: num ** 2
multiplicacao = lambda x,y: x*y

print(quadrado(2))
print(multiplicacao(2,3))

### Map

In [ ]:
import math
lista1 = [1, 4, 9, 16, 25]
lista2 = map(math.sqrt, lista1)
print(list(lista2))

In [ ]:
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
from math import log10
print (list(map(log10, nums)))
print()
print (list(map(lambda x: x / 3, nums)))

### Reduce

In [ ]:
from functools import reduce
nums = range(100)
print (reduce(lambda x, y: x + y, nums))

In [ ]:
f = lambda a,b: a if (a > b) else b
print(reduce(f, [47,11,42,102,13]))

### Filter

In [ ]:
y = [1,2,3,4,5,6,7]
print(list(filter(lambda x: x % 2, y)))

In [ ]:
number_list = range(-5, 5)
less_than_zero = list(filter(lambda x: x < 0, number_list))
print(less_than_zero)

### Transposição

In [ ]:
x = [1, 2, 3]
y = [4, 5, 6]
print (list(zip(x, y)))

In [ ]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print (list(zip(*matriz))) #Descompacta e depois faz a transposição

### List Comprehension

In [ ]:
S = [x*2 for x in range(0, 10)]
print(S)

In [ ]:
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
print ([ x**2 for x in nums if x % 2 ])

In [ ]:
[[s.capitalize(), s.upper(), len(s)] for s in ['um', 'dois', 'tres']]


## TODO Section

## 1)
A amplitude de um vetor 3D é dado pela seguinte fórmula: $\sqrt{x^2 + y^2 + z^2}$

Escreva uma função, usando lambda, que calcule a amplitude de qualquer vetor. Exemplo de entrada:

    -> (1,1,1) 
    -> (3,4,5)

In [ ]:
# resposta
import math
def amplitude(vetor):
    return math.sqrt(sum([x**2 for x in vetor]))

l = [(1,1,1),(3,4,5)]
for v in l:
    print('A amplitude do vetor %s é %.2f' % (str(v), amplitude(v)))

In [ ]:
# Resposta lambda
amplitude = lambda x,y,z:math.sqrt(x**2 + y**2 + z**2)
amplitude(3,4,5)

## 2) 
Use reduce para criar uma função que calcule o fatorial de qualquer número n

In [ ]:
# resposta
from functools import reduce
def fatorial(n):
    return reduce(lambda x, y: x*y, range(2,n+1))

#Uso
n = int(input('Calcule o fatorial de : '))
print(fatorial(n))

# Numpy

In [1]:
import numpy as np
list1 = [0,1,2,3,4]
arr1d = np.array(list1)
# principal diferença entre list e array
print(arr1d + 2)
print(list1 + 2)  # erro

[2 3 4 5 6]


TypeError: can only concatenate list (not "int") to list

In [ ]:
type(arr1d)

In [ ]:
x = [1,2,3,4.5,5.7]
print('--------- lists ----------\n')
print(type(x))
print(x)
print(type(x[1]))
print(type(x[4]))
print('\n')
print('--------- array ----------\n')
y = np.array(x)
print(type(y))
print(y)
print(type(y[1]))
print(type(y[4]))

## ndarray

In [ ]:
import numpy as np
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

In [ ]:
print(arr1.shape)
print(arr1.dtype)

In [ ]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
print()
print(arr2.ndim)
print()
print(arr2.shape)
print()
print(arr2.dtype)
print()
print(arr2.size)

In [ ]:
data3 = np.zeros(10)
data4 = np.ones(10)
data5 = np.empty([2,2])
print(data3)
print()
print(data4)
print()
print(data5)

In [ ]:
data6 = np.arange(15)
print(data6)

In [ ]:
data7 = np.eye(5)
print(data7)

In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
print(arr1.dtype)
arr2 = np.array([1, 2], dtype=np.int32)
print(arr2.dtype)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

In [ ]:
float_arr

In [ ]:
arr2 = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr2)
arr2.astype(np.int32)

In [ ]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

## Operações entre arrays e escalares

In [ ]:
arr3 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr3)
print()
print('Multiplicação: \n',arr3 * arr3)
print()
print('Subtração: \n',arr3 - arr3)

In [ ]:
arr3 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr3)
print('Escalar dividindo array: \n',1/arr3)
print('Tirando Raiz quadrada de cada elemento: \n',arr3 ** 0.5)

## Indexação e Fatiamento

In [ ]:
#arr = [2,14,3,6,8,3,10,222,4]
arr = np.arange(10)
print(arr)
print()
print(arr[5])
print()
print(arr[5:8])
print()
arr[5:8] = 12
print(arr)

In [ ]:
arr_slice = arr[5:8]
print(arr_slice)
arr_slice[1] = 12345
print(arr_slice)
print(arr)

In [3]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)
print()
print(arr2d[2])
print()
print(arr2d[2][2]) #igual a print(arr2d[0, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[7 8 9]

9


In [ ]:
arr2d[2:,:]

In [ ]:
print(arr2d[:2, 1:])
print(arr2d[1, :2])
print(arr2d[:, :1])

## TODO

### 3)

Seja um array, A = [10,3,7,5,8,23,15] e dois escalares, x = 6, y = 20. 

Crie uma função que retorne um novo array contendo elementos no intervalo [6,20]

In [ ]:
# Resposta
import numpy as np
def interval(vetor,x = 6,y = 20):
    return np.sort(vetor[(vetor > x) & (vetor < y)])

In [ ]:
vetor = np.array([10,3,7,5,8,23,15])
interval(vetor)

## 4)

Escreva um programa usando Numpy que adiciona os valores de um vetor a cada linha de uma matriz. 

Obs: o tamanho do vetor tem de ser o mesmo da quantidade de linhas

vetor = [ 1 1 0]

matriz = [[1 2 3]; [4 5 6]; [7 8 9]]

resultado = [[2 3 3; 5 6 6; 8 9 9]]


Essa função pode ajudar: np.empty_like() 

In [ ]:
# Resposta
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
v = np.array([1, 1, 0])
result = np.empty_like(m)
print(result)
print()
for i in range(m.shape[0]):
    result[i, :] = m[i, :] + v
print(result)

In [ ]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
m.shape[0]

## Transposição

In [2]:
arr = np.arange(15).reshape((3, 5))
print(arr)
print()
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [4]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Flattening

In [5]:
print('----- flatten() -----\n')
print(arr2d.flatten())
b1 = arr2d.flatten() 
b1[0] = 100
print(arr2d,'\n')
print('----- ravel() -----\n')
b2 = arr2d.ravel() 
b2[0] = 101
print(arr2d)

----- flatten() -----

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

----- ravel() -----

[[101   2   3]
 [  4   5   6]
 [  7   8   9]]


In [6]:
arr2d.ravel()

array([101,   2,   3,   4,   5,   6,   7,   8,   9])

## Funções Universais

In [7]:
arr = np.arange(10)
print(arr)
print(np.sqrt(arr)) #raiz quadrada
print()
np.exp(arr) #e^x

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]



array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

## Localização baseada em Condição e Métodos Estatísticos

In [8]:
import numpy as np
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [9]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [10]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [11]:
arr = np.random.randn(4, 4)
print(arr)
print()
print(np.where(arr > 0, 2, -2)) # atribui 2 p/ x>0, -2 caso contrário
print()
print(np.where(arr > 0, 2, arr)) # atribui 2 p/ x>0, mantém original caso contrário

[[ 1.35855113 -2.04521429 -0.32271891 -0.88566806]
 [ 0.438977   -1.14625045 -0.93500582  1.16038918]
 [ 0.56767943  0.0281511   0.38551214 -0.72904941]
 [-0.92410496 -0.1960051  -0.83841474  0.14439254]]

[[ 2 -2 -2 -2]
 [ 2 -2 -2  2]
 [ 2  2  2 -2]
 [-2 -2 -2  2]]

[[ 2.         -2.04521429 -0.32271891 -0.88566806]
 [ 2.         -1.14625045 -0.93500582  2.        ]
 [ 2.          2.          2.         -0.72904941]
 [-0.92410496 -0.1960051  -0.83841474  2.        ]]


In [12]:
arr = np.random.randn(5, 4)
print(arr)
print()
print(arr.mean()) #ou np.mean(arr)
print()
print(arr.sum())
print()
print(arr.mean(axis=1)) #linhas
print()
print(arr.mean(axis=0)) # colunas

[[-0.50147505 -0.45088634 -0.70370366  1.51728305]
 [-0.13317089  0.68153919  1.38086361  0.58643632]
 [-1.03244897  0.34304937 -0.07541401  0.56424381]
 [-0.64143232  0.02426337  0.18844768  0.10866445]
 [-0.64778399 -0.83627509  0.43360836  1.04515633]]

0.09254826150033478

1.8509652300066957

[-0.0346955   0.62891706 -0.05014245 -0.0800142  -0.0013236 ]

[-0.59126224 -0.0476619   0.2447604   0.76435679]


 ## Álgebra Linear

In [13]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x)
print()
print(y)
print()
z = np.matmul(x,y) #igual aa np.dot(x,y)
print(z)

[[1. 2. 3.]
 [4. 5. 6.]]

[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]

[[ 28.  64.]
 [ 67. 181.]]


In [14]:
print(x.shape)
print(y.shape)
print(z.shape)

(2, 3)
(3, 2)
(2, 2)


In [15]:
import numpy as np
from numpy.linalg import inv
X = np.random.randn(5, 5)
print(X)
mat = np.matmul(X.T,X) #transposta * X
print()
print(mat)
print()
print(inv(mat)) #inversa

[[ 0.40292984  0.89196547  0.59360748  0.30007443  0.52709294]
 [ 1.42166047 -0.34945559  0.27439398 -0.96770017  0.54492464]
 [-2.65576021  1.34962992  0.47916669  1.34113977  1.59025684]
 [-0.48609851  1.59894287 -1.10782301  1.91651405  0.25325415]
 [-0.53485581 -0.62669472  0.75181967  1.25292077 -0.68510401]]

[[ 9.75889578 -4.16375358 -0.5068786  -6.41832436 -2.99293616]
 [-4.16375358  5.68858711 -1.16222055  4.69506428  3.26026994]
 [-0.5068786  -1.16222055  2.44976725 -0.62596306  0.42877302]
 [-6.41832436  4.69506428 -0.62596306  8.06798073  1.39058422]
 [-2.99293616  3.26026994  0.42877302  1.39058422  3.63719182]]

[[ 0.35340994 -0.34671155 -0.06954158  0.39868721  0.45736275]
 [-0.34671155  2.05891545  0.94756566 -1.08546865 -1.82755297]
 [-0.06954158  0.94756566  0.89526243 -0.38843406 -0.86362436]
 [ 0.39868721 -1.08546865 -0.38843406  0.86769169  1.01510122]
 [ 0.45736275 -1.82755297 -0.86362436  1.01510122  2.00316313]]


## Geração de Números Aleatórios

#### Você pode ver todas as distribuições nesse link: [numpy random](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html)

In [16]:
# gera 4 números aleatórios
# entre [0.0,1.0)
samples = np.random.random(4)
samples

array([0.6924069 , 0.95560631, 0.39523608, 0.91582222])

In [17]:
# A geração de números é determinística
# Ou seja, é baseada num estado interno
# que chamamos de seed
np.random.seed(42) # set seed
print(np.random.random())
np.random.seed(0) # reset seed
print()
print(np.random.random())

0.3745401188473625

0.5488135039273248


In [18]:
# shuffle reordena um array
# é muito usado antes do processo
# de treino de algoritmo de ML
x = np.arange(10)
np.random.shuffle(x)
x

array([2, 8, 4, 9, 1, 6, 7, 3, 0, 5])

## Vectorize

In [ ]:
import numpy as np

In [19]:
def modulo(x):
    if x % 2 == 1:
        return x**2
    else:
        return x/2
    
print('x = 10 retorna ', modulo(10))
print('x = 11 retorna ', modulo(11))
print('x = [10, 11, 12] retorna ', modulo([10, 11, 12])) # Erro

x = 10 retorna  5.0
x = 11 retorna  121


TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [20]:
modulo_vect = np.vectorize(modulo, otypes=[float])

print('x = [10, 11, 12] retorna ', modulo_vect([10, 11, 12]))
print('x = [[10, 11, 12], [1, 2, 3]] retorna ', modulo_vect([[10, 11, 12], [1, 2, 3]]))

x = [10, 11, 12] retorna  [  5. 121.   6.]
x = [[10, 11, 12], [1, 2, 3]] retorna  [[  5. 121.   6.]
 [  1.   1.   9.]]


## Aplicar uma função – coluna ou linha

In [21]:
#criando matriz
np.random.seed(100)
arr_x = np.random.randint(1,10,size=[4,10])
arr_x

array([[9, 9, 4, 8, 8, 1, 5, 3, 6, 3],
       [3, 3, 2, 1, 9, 5, 1, 7, 3, 5],
       [2, 6, 4, 5, 5, 4, 8, 2, 2, 8],
       [8, 1, 3, 4, 3, 6, 9, 2, 1, 8]])

In [22]:
#função que calcula diferença
def max_minus_min(x):
    return np.max(x) - np.min(x)

# aplicando nas linhas
print('Por linha: ', np.apply_along_axis(max_minus_min, 1, arr=arr_x))

# aplicando nas colunas
print('Por coluna: ', np.apply_along_axis(max_minus_min, 0, arr=arr_x))

Por linha:  [8 8 6 8]
Por coluna:  [7 8 2 7 6 5 8 5 5 5]


## Outros Métodos

In [23]:
bools = np.array([False, False, True, False])
print(bools.any()) # se houver pelo menos um True
print(bools.all()) # se todos forem True

True
False


In [24]:
arr = np.random.randn(8)
print(arr)
arr.sort() #in-place arr = arr.sort()
print(arr)

[-0.46402358 -0.05702664  0.27592974  1.49451522  0.56682064 -2.30337426
  1.37700072 -1.18738682]
[-2.30337426 -1.18738682 -0.46402358 -0.05702664  0.27592974  0.56682064
  1.37700072  1.49451522]


In [25]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
print(np.unique(ints))

['Bob' 'Joe' 'Will']
[1 2 3 4]


In [26]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

## TODO Section

### 5)
Suponha dois arrays, A = [1,4,2,6,5,7,3,0] e B = [3,2,0,9,8,7]. 

Remove de A todo elemento pertencente a B


In [29]:
# resposta
import numpy as np
a = np.array([1,4,2,6,5,7,3,0])
b = np.array([3,2,0,9,8,7])

np.setdiff1d(a,b)

array([1, 4, 5, 6])

### 6)

A célula abaixo faz o download de um dataset e armazena na variável iris_2d. Em seguida, substitui alguns de seus elementos por NaN. Resolva as questões que se seguem:

In [27]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [28]:
iris_2d

array([[5.1, 3.5, 1.4, nan],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, nan, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, nan, 0.2],
       [4.9, 3

a) Encontre o número de NaN na primeira coluna

b) Encontre o número total de NaN

c) Encontre as posições (número da linha) de NaN na primeira coluna

d) Substitua todos os NaN por 0

In [30]:
# Resposta
print("Número de NaN na primeira coluna: ", np.isnan(iris_2d[:, 0]).sum(),"\n")

print("Número total de NaN: ", np.isnan(iris_2d).sum(),"\n")

print("Posições de NaN na primeira coluna: ", np.where(np.isnan(iris_2d[:, 0])), "\n")

print("Substituindo NaN por 0: ")
iris_2d[np.isnan(iris_2d)] = 0

Número de NaN na primeira coluna:  4 

Número total de NaN:  20 

Posições de NaN na primeira coluna:  (array([ 38,  58,  71, 131], dtype=int64),) 

Substituindo NaN por 0: 


In [31]:
iris_2d[:8]

array([[5.1, 3.5, 1.4, 0. ],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 0. , 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2]])